version: 2
updates:
    -   package-ecosystem: "maven"
        directory: "/"
        schedule:
            interval: "weekly"
            interval: "daily"
            time: "22:27"
            timezone: "Asia/Kolkata"
        # Allow up to 10 open pull requests for pip dependencies
        open-pull-requests-limit: 1
